CREATE TABLE `redhelp_db`.`BLOOD_REQUEST` (
  `B_R_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `PATIENT_NAME` VARCHAR(50),
  `DESCRIPTION` VARCHAR(400),
  `UNITS` VARCHAR(20),
  `PHONE_NUMBER` VARCHAR(15),
  `LOCATION_LAT` DOUBLE,
  `LOCATION_LONG` DOUBLE,
  `ACTIVE` BOOLEAN NOT NULL,
  PRIMARY KEY (`B_R_ID`)
)
CHARACTER SET utf8
COMMENT = 'Table containing blood request details.';
CREATE TABLE `redhelp_db`.`BLOOD_GROUP_TYPE` (
  `B_G_T_ID` BIGINT(20) NOT NULL,
  `NAME` INT NOT NULL,
  PRIMARY KEY (  `B_G_T_ID`)
)
CHARACTER SET utf8;
